/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SitePricingRouteImport } from './routes/_site.pricing'
import { Route as SiteGalleryRouteImport } from './routes/_site.gallery'
import { Route as SiteContactRouteImport } from './routes/_site.contact'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGalleryRoute = SiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/pricing': typeof SitePricingRoute
}
export interface FileRoutesByTo {
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/pricing': typeof SitePricingRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/contact': typeof SiteContactRoute
  '/_site/gallery': typeof SiteGalleryRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/gallery' | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to: '/contact' | '/gallery' | '/pricing' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/contact'
    | '/_site/gallery'
    | '/_site/pricing'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/gallery': {
      id: '/_site/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof SiteGalleryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteContactRoute: typeof SiteContactRoute
  SiteGalleryRoute: typeof SiteGalleryRoute
  SitePricingRoute: typeof SitePricingRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContactRoute: SiteContactRoute,
  SiteGalleryRoute: SiteGalleryRoute,
  SitePricingRoute: SitePricingRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
